name: CI

on: [push, pull_request]

jobs:
  test:
    if: "!contains(github.event.head_commit.message, '[skip-ci]')"
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:

      - name: Git Checkout
        id: git_checkout
        uses: actions/checkout@v2

      - name: Setup Python
        id: setup_python
        uses: actions/setup-python@v1
        with:
          python-version: '3.7'

      - name: Setup Test Environment
        id: setup_test_environment
        run: |
          python -m pip install pipenv
          pipenv install --dev
          short_sha=${GITHUB_SHA::8}
          echo "SHORT_SHA=${short_sha}" >> $GITHUB_ENV

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image For testing
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: false # don't push before testing
          tags: sagebionetworks/${{ github.event.repository.name }}:${{ env.SHORT_SHA }}

      - name: Edit CWL file tool version
        id: edit_cwl
        run: |
          tools_dir=cwl
          new_version=${{ env.SHORT_SHA }}
          pipenv run utils/bump_cwl_version.py $tools_dir $new_version

      - name: Test CWL
        id: test_cwl
        run: |
          pipenv run cwltest --test tests/test-descriptions.yaml --tool cwl-runner

  build:
    if: >-
      !contains(github.event.head_commit.message, '[skip-ci]')
      &&
      github.event_name == 'push'
      &&
      github.ref == 'refs/heads/main'
    needs: test
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:

      - name: Git Checkout
        id: git_checkout
        uses: actions/checkout@v2

      - name: Setup Python
        id: setup_python
        uses: actions/setup-python@v1
        with:
          python-version: '3.7'

      - name: Setup Build Environment
        id: setup_build_environment
        run: |
          python -m pip install pipenv
          pipenv install

      - name: Calculate Next Autotagging Version
        id: calc_version
        uses: mathieudutour/github-tag-action@v4.2
        with:
          dry_run: true # calculate the next version without actually tagging
          release_branches: main

      - name: Set Env Vars
        id: set_version_env_vars
        run: |
          new_version=${{ steps.calc_version.outputs.new_version }}
          new_tag=${{ steps.calc_version.outputs.new_tag }}
          echo "NEW_VERSION=${new_version}" >> $GITHUB_ENV
          echo "NEW_GIT_TAG=${new_tag}" >> $GITHUB_ENV

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Publish Docker Image
        id: docker_publish
        uses: docker/build-push-action@v2
        with:
          tags: |
            sagebionetworks/${{ github.event.repository.name }}:${{ env.NEW_VERSION }}
            sagebionetworks/${{ github.event.repository.name }}:latest

      - name: Edit CWL file tool version
        id: edit_cwl
        run: |
          tools_dir=cwl
          new_version=${{ env.NEW_VERSION }}
          pipenv run utils/bump_cwl_version.py $tools_dir $new_version

      - name: Commit, Tag, Push
        id: commit_tag_push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -a -m "Update docker image version in CWL tool to ${{ env.NEW_VERSION }}"
          git tag ${{ env.NEW_GIT_TAG }}
          git push && git push --tags
